[package]
name = "client-auth-test"
version = "0.1.0"
authors = ["momothereal <momothereal.mc@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.35"
tokio = "0.1.22"
tokio-rustls = "0.10.1"
rustls = "0.16.0"
openssl = "0.10.48"
